// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "github.com/emurmotol/pbgrpc/ethereum/pkg/endpoint"
	pb "github.com/emurmotol/pbgrpc/ethereum/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	createAccount grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.EthereumServer {
	return &grpcServer{createAccount: makeCreateAccountHandler(endpoints, options["CreateAccount"])}
}
